on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu
    steps:
    - uses: actions/checkout@1
    - name: Snapcraft setup
      uses: samuelmeuli/action-snapcraft@v1.2.0
    - name: Build
      run: snapcraft --version
    
